name: adhara_socket_io
description: Websocket by socket.io for flutter by adhara, supports both iOS and Android
version: 0.4.2+1
homepage: https://github.com/infitio/flutter_socket_io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.infitio.adharasocketio
        pluginClass: AdharaSocketIoPlugin
      ios:
        pluginClass: AdharaSocketIoPlugin
      macos:
        pluginClass: AdharasocketioPlugin
